// <auto-generated />
namespace Puzzles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changedpricetodecimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedpricetodecimal));
        
        string IMigrationMetadata.Id
        {
            get { return "201608050419508_Changed price to decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
